# -*- coding: utf-8 -*-
import logging
from django.core.management.base import BaseCommand
from organizations.models import Party
from positions.models import Position

logger = logging.getLogger("commands")


class Command(BaseCommand):
    """ """

    help = "Update Parties"
    parties_cache = {}
    parties_group = {
        "0": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI (PSOE)",
            "UCD": "UNION DE CENTRO DEMOCRATICO",
            "AP": "UNIÓN NACIONAL ESPAÑOLA,ACCIÓN DEMOCRÁTICA ESPAÑOLA,UNIÓN CATALANA,UNIÓN DEMOCRÁTICA,CLUB CATALONIA,REFORMA DEMOCŔATICA",
            "PCE": "PARTIDO COMUNISTA DE ESPAÑA",
            "PCE-PCPV": "PARTIDO COMUNISTA DEL PAIS VALENCIANO- PARTIT COMUNISTA DEL PAIS VALENCIA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "PDC": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,PARTIT SOCIALISTA DE CATALUNYA-REAGRUPAMENT,ESQUERRA DEMOCRÀTICA DE CATALUNYA,FRONT NACIONAL DE CATALUNYA",
            "EE": "EUSKAL IRAULTZARAKO ALDERDIA,EUSKADIKO MUGIMENDU KOMUNISTA",
            "CIC": "CANDIDATURA INDEPENDIENTE DE CENTRO",
            "PSUC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA",
            "CAIC": "CANDIDATURA ARAGONESA INDEPENDIENTE DE CENTRO",
            "UCIDCC": "UNIÓ DEL CENTRE I LA DEMOCRÀCIA CRISTIANA DE CATALUNYA",
            "EC": "PARTIT DEL TREBALL DE CATALUNYA,ESQUERRA REPUBLICANA DE CATALUNYA,ESTAT CATALA",
            "US-PSP": "PARTIDO SOCIALISTA POPULAR,PARTIDO SOCIALISTA DE ARAGÓN,PARTIDO SOCIALISTA DE ANDALUCIA,PARTIDO SOCIALISTA AUTONOMISTA DE CANARIAS,PARTIDO SOCIALISTA DE LA REGIÓN MURCIANA,PARTIT SOCIALISTA DE LES ILLES,MOVIMENT SOCIALISTA DE MENORCA,PARTIT SOCIALISTA DEL PAÍS VALENCIÀ",  # Unidad Socialista-Partido Socialista Popular
            "US": "PARTIDO SOCIALISTA POPULAR,PARTIDO SOCIALISTA DE ARAGÓN,PARTIDO SOCIALISTA DE ANDALUCIA,PARTIDO SOCIALISTA AUTONOMISTA DE CANARIAS,PARTIDO SOCIALISTA DE LA REGIÓN MURCIANA,PARTIT SOCIALISTA DE LES ILLES,MOVIMENT SOCIALISTA DE MENORCA,PARTIT SOCIALISTA DEL PAÍS VALENCIÀ",  # Unidad Socialista
        },
        "1": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI (PSOE)",
            "UCD": "UNION DE CENTRO DEMOCRATICO",
            "CC-UCD": "UNION DE CENTRO DEMOCRATICO",
            "CD": "ALIANZA POPULAR,ACCION CIUDADANA LIBERAL,PARTIDO DEMÓCRATA PROGRESISTA,RENOVACIÓN ESPAÑOLA,PARTIDO POPULAR DE CATALUÑA,PARTIDO ECOLÓGICO ESPAÑOL,ACCIÓN POR CEUTA,ASOCIACIÓN DE DEMÓCRATAS INDEPENDIENTES VASCOS,CONFEDERACIÓN DE PARTIDOS CONSERVADORES,CENTRO POPULAR",
            "PCE": "PARTIDO COMUNISTA DE ESPAÑA",
            "PCPV": "PARTIDO COMUNISTA DE ESPAÑA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "PSA": "PARTIDO SOCIALISTA DE ANDALUCIA",
            "PAR": "PARTIDO ARAGONES",
            "UPN": "UNION DEL PUEBLO NAVARRO",
            "UPC": "UNION DEL PUEBLO CANARIO",
            "PSUC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA",
            "UN": "FUERZA NUEVA,FALANGE ESPAÑOLA DE LAS J.O.N.S.,CÍRCULOS DOCTRINALES JOSÉ ANTONIO,COMUNION TRADICIONALISTA,AGRUPACION DE JUVENTUDES TRADICIONALISTAS",
        },
        "2": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "UCD": "UNION DE CENTRO DEMOCRATICO",
            "CDS": "CENTRO DEMOCRATICO Y SOCIAL",
            "CD": "ALIANZA POPULAR,ACCION CIUDADANA LIBERAL,PARTIDO DEMÓCRATA PROGRESISTA,RENOVACIÓN ESPAÑOLA,PARTIDO POPULAR DE CATALUÑA,PARTIDO ECOLÓGICO ESPAÑOL,ACCIÓN POR CEUTA,ASOCIACIÓN DE DEMÓCRATAS INDEPENDIENTES VASCOS,CONFEDERACIÓN DE PARTIDOS CONSERVADORES,CENTRO POPULAR",
            "PCE": "PARTIDO COMUNISTA DE ESPAÑA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "PSUC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA",
        },
        "3": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSC": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "CP": "AP,PDP,PL,UNION DEL PUEBLO NAVARRO,CdG",
            "IU": "IZQUIERDA UNIDA",
            "UEC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA,ENE",
            "CDS": "CENTRO DEMOCRATICO Y SOCIAL",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "CG": "CG",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "UV": "UNIO VALENCIANA",
            "AIC": "AGRUPACIONES INDEPENDIENTES DE CANARIAS",
            "PAR": "PARTIDO ARAGONES",
        },
        "4": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-A": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI (PSOE)",
            "PP": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PP-CG": "PARTIDO POPULAR,CG",
            "CDS": "CENTRO DEMOCRATICO Y SOCIAL",
            "IU": "IZQUIERDA UNIDA",
            "IU-A": "IU",
            "IU-CA": "IU",
            "IU-EU": "IU",
            "IU-EUPV": "IZQUIERDA UNIDA,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "IC": "IC",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "EA": "EA",
            "PA": "PA",
            "UV": "UNIO VALENCIANA",
            "PAR": "PARTIDO ARAGONES",
            "AIC": "AGRUPACIONES INDEPENDIENTES DE CANARIAS",
        },
        "5": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-A": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "IU": "IZQUIERDA UNIDA",
            "IU-A": "IU",
            "IU-CA": "IU",
            "IU-EU": "IU",
            "IU-EUPV": "IZQUIERDA UNIDA,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EA-EE": "EA,EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "IC": "IC",
            "CC": "CC",
            "UV": "UNIO VALENCIANA",
            "HB": "HERRI BATASUNA",
            "PAR": "PARTIDO ARAGONES",
        },
        "6": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-A": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "IU": "IZQUIERDA UNIDA",
            "IU-LV": "IU",
            "IU-LV-CA": "IZQUIERDA UNIDA LOS VERDES-CONVOCATORIA POR ANDALUCIA",
            "IU-EUPV": "IZQUIERDA UNIDA,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "EUPV": "ESQUERRA UNIDA DEL PAIS VALENCIA",
            "IU-EB": "IU",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EA": "EA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "BNG": "BNG",
            "CC": "CC",
            "UV": "UNIO VALENCIANA",
            "IC-EV": "ICV",
        },
        "7": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-PROGRESISTAS": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC(PSC-PSOE)": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSDEG-PSOE-PROGRESISTAS": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE (PSOE-PROGRESISTAS)": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "PP-UPN": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PP-UPM": "PARTIDO POPULAR,UPM",
            "IU": "IU",
            "IU-CM": "IZQUIERDA UNIDA DE LA COMUNIDAD DE MADRID",
            "EUPV": "ESQUERRA UNIDA DEL PAIS VALENCIA",
            "IU-LV-CA": "IZQUIERDA UNIDA LOS VERDES-CONVOCATORIA POR ANDALUCIA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "IC-V": "ICV",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EA": "EA",
            "CC": "CC",
            "CHA": "CHUNTA ARAGONESISTA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "PA": "PA",
        },
        "8": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC(PSC-PSOE)": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOEDEANDALUCÍA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE(PSOE)": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "PPDEC": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "IU": "IZQUIERDA UNIDA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "NA-BAI": "Aralar,EA,Batzarre,PNV",
            "EA": "EA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "CC": "CC",
            "NC": "NUEVA CANARIAS",
            "CHA": "CHUNTA ARAGONESISTA",
        },
        "9": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC(PSC-PSOE)": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE(PSOE)": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOEDEANDALUCÍA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "IU-ALTERNATIVA": "IU",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "UPN": "UNION DEL PUEBLO NAVARRO",
            "NA-BAI": "Aralar,EA,Batzarre,EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "UPYD": "UNION PROGRESO Y DEMOCRACIA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "CC-PNC": "CC,PARTIDO NACIONALISTA CANARIO",
        },
        "10": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PP": "PARTIDO POPULAR",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "PP-EU": "PARTIDO POPULAR,EU",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "IZQ-PLU": "IU",
            "IU-IX": "IZQUIERDA UNIDA DE ASTURIAS-IZQUIERDA XUNIDA D'ASTURIES",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC-RI.CAT": "ESQUERRA REPUBLICANA DE CATALUNYA,CatSí",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "UPYD": "UNION PROGRESO Y DEMOCRACIA",
            "CC-NC-PNC": "CC,PARTIDO NACIONALISTA CANARIO,NUEVA CANARIAS",
            "GB": "GS,PNV,AT",
            "AMAIUR": "EA,Alternatiba,Aralar",
            "FORO": "FORO",
            "COMPROMÍS-Q": "Més,IdPV,VERDES EQUO",
        },
        "11": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSOE-NCA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL,NUEVA CANARIAS",
            "PP": "PARTIDO POPULAR",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "PP-FORO": "PARTIDO POPULAR,FORO",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PODEMOS": "PODEMOS",
            "PODEMOS-EN MAREA-ANOVA-EU": "PODEMOS,EM,Anova,IZQUIERDA UNIDA",
            "PODEMOS-COMPROMÍS": "PODEMOS,Més,IdPV,VERDES EQUO",
            "POD-AAA EN COMÚN": "PODEMOS,AAeC",
            "EN COMÚ": "PODEMOS,CATALUNYA EN COMÚ",
            "IU-UPEC": "IU",
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "ERC-CATSÍ": "ESQUERRA REPUBLICANA DE CATALUNYA,CatSí",
            "DL": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,DC",
            "CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO",
        },
        "12": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSDG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-NCA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL,NUEVA CANARIAS",
            "PP": "PARTIDO POPULAR",
            "PP-FORO": "PARTIDO POPULAR,FORO",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "UP": "PODEMOS,IZQUIERDA UNIDA,VERDES EQUO",
            "ECP": "PODEMOS,CATALUNYA EN COMÚ,IZQUIERDA UNIDA",
            "EM-P-A-EU": "EM,PODEMOS,Anova,IZQUIERDA UNIDA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "CDC": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA",
            "ERC-CATSÍ": "ESQUERRA REPUBLICANA DE CATALUNYA,CatSí",
            "CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO",
            "C-P-EUPV": "Més,IdPV,VERDES EQUO,PODEMOS,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "UPM": "PODEMOS,IZQUIERDA UNIDA,Més",
        },
        "13": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "PP-FORO": "PARTIDO POPULAR,FORO",
            "UP": "PODEMOS,IZQUIERDA UNIDA,VERDES EQUO",
            "ECP": "PODEMOS,CATALUNYA EN COMÚ,IZQUIERDA UNIDA",
            "EC-UP": "PODEMOS,IZQUIERDA UNIDA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "JXCAT-JUNTS": "PARTIT DEMÒCRATA EUROPEU CATALÀ,CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,Junts",
            "ERC-S": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "VOX": "VOX",
            "CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO",
            "NA+": "UPN,PARTIDO POPULAR,CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "PRC": "PARTIDO REGIONALISTA DE CANTABRIA",
            "C:B-I-V": "Més,IdPV,VERDES EQUO",
        },
        "14": {
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSE-EE-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "PP-FORO": "PARTIDO POPULAR,FORO",
            "UP": "PODEMOS,IZQUIERDA UNIDA,VERDES EQUO",
            "ECP-GUAYEM EL CANVI": "PODEMOS,CATALUNYA EN COMÚ,IZQUIERDA UNIDA",
            "EC-UP": "PODEMOS,IZQUIERDA UNIDA",
            "MÁS PAÍS-EQUO": "MP,VERDES EQUO",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "JXCAT-JUNTS": "PARTIT DEMÒCRATA EUROPEU CATALÀ,CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,Junts",
            "JXCAT-JUNTS (JUNTS)": "PARTIT DEMÒCRATA EUROPEU CATALÀ,CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,Junts",
            "JXCAT-JUNTS (PDECAT)": "PARTIT DEMÒCRATA EUROPEU CATALÀ,CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,Junts",
            "ERC-S": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "CUP-PR": "CANDIDATURA D'UNITAT POPULAR",
            "CCA-PNC-NC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO,NUEVA CANARIAS",
            "NC-CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO,NUEVA CANARIAS",
            "NA+": "UNION DEL PUEBLO NAVARRO,PARTIDO POPULAR,CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "¡TERUEL EXISTE!": "TERUEL EXISTE",
            "MÉS COMPROMÍS": "Més",
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "VOX": "VOX",
            "PRC": "PARTIDO REGIONALISTA DE CANTABRIA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
        },
    }

    def get_positions(self, institution_name):
        return Position.objects.filter(
            period__institution__name=institution_name,
            period__number__gte=0,
        )

    def get_party(self, short_name):
        short_name = short_name.strip().upper()
        short_name = self.parties_group.get(short_name, short_name)
        result = self.parties_cache.get(short_name)
        if result:
            return result
        result = Party.objects.filter(short_name__iexact=short_name).first()
        if result:
            self.parties_cache[short_name] = result
            return result
        return None

    def handle_special_cases(self, position):
        leg = position.metadata["www.congreso.es"]["idLegislatura"]
        code = position.metadata["www.congreso.es"]["codParlamentario"]

        if leg == 8 and code == 331:
            return "PARTIDO POPULAR"

        return None

    def handle(self, *args, **options):
        for position in self.get_positions("Parlamento de España"):
            name = position.metadata["www.congreso.es"]["formacion"].strip().upper()

            if self.handle_special_cases(position):
                continue

            if not self.parties_group[str(position.period.number)].get(name):
                print(name, "                 ->", position)

        parties = set()

        for leg in self.parties_group:
            for coa in self.parties_group[leg]:
                for party in self.parties_group[leg][coa].split(","):
                    parties.add(party)

        for party in sorted(parties):
            print(party)
