# -*- coding: utf-8 -*-
import logging
from django.core.management.base import BaseCommand
from organizations.models import Party
from positions.models import Position

logger = logging.getLogger("commands")


class Command(BaseCommand):
    """ """

    help = "Update Parties"
    parties_cache = {}
    parties_group = {
        "0": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_1977
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI (PSOE)",
            "UCD": "UNION DE CENTRO DEMOCRATICO",
            "AP": "UNIÓN NACIONAL ESPAÑOLA,ACCIÓN DEMOCRÁTICA ESPAÑOLA,UNIÓN CATALANA,UNIÓN DEMOCRÁTICA,CLUB CATALONIA,REFORMA DEMOCŔATICA",
            "PCE": "PARTIDO COMUNISTA DE ESPAÑA",
            "PCE-PCPV": "PARTIDO COMUNISTA DEL PAIS VALENCIANO- PARTIT COMUNISTA DEL PAIS VALENCIA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "PDC": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,PARTIT SOCIALISTA DE CATALUNYA-REAGRUPAMENT,ESQUERRA DEMOCRÀTICA DE CATALUNYA,FRONT NACIONAL DE CATALUNYA",
            "EE": "EUSKAL IRAULTZARAKO ALDERDIA,EUSKADIKO MUGIMENDU KOMUNISTA",
            "CIC": "CANDIDATURA INDEPENDIENTE DE CENTRO",
            "PSUC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA",
            "CAIC": "CANDIDATURA ARAGONESA INDEPENDIENTE DE CENTRO",
            "UCIDCC": "UNIÓ DEL CENTRE I LA DEMOCRÀCIA CRISTIANA DE CATALUNYA",
            "EC": "PARTIT DEL TREBALL DE CATALUNYA,ESQUERRA REPUBLICANA DE CATALUNYA,ESTAT CATALA",
            "US-PSP": "PARTIDO SOCIALISTA POPULAR,PARTIDO SOCIALISTA DE ARAGÓN,PARTIDO SOCIALISTA DE ANDALUCIA,PARTIDO SOCIALISTA AUTONOMISTA DE CANARIAS,PARTIDO SOCIALISTA DE LA REGIÓN MURCIANA,PARTIT SOCIALISTA DE LES ILLES,MOVIMENT SOCIALISTA DE MENORCA,PARTIT SOCIALISTA DEL PAÍS VALENCIÀ",  # Unidad Socialista-Partido Socialista Popular
            "US": "PARTIDO SOCIALISTA POPULAR,PARTIDO SOCIALISTA DE ARAGÓN,PARTIDO SOCIALISTA DE ANDALUCIA,PARTIDO SOCIALISTA AUTONOMISTA DE CANARIAS,PARTIDO SOCIALISTA DE LA REGIÓN MURCIANA,PARTIT SOCIALISTA DE LES ILLES,MOVIMENT SOCIALISTA DE MENORCA,PARTIT SOCIALISTA DEL PAÍS VALENCIÀ",  # Unidad Socialista
        },
        "1": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_1979
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI (PSOE)",
            "UCD": "UNION DE CENTRO DEMOCRATICO",
            "CC-UCD": "UNION DE CENTRO DEMOCRATICO",
            "CD": "ALIANZA POPULAR,ACCION CIUDADANA LIBERAL,PARTIDO DEMÓCRATA PROGRESISTA,RENOVACIÓN ESPAÑOLA,PARTIDO POPULAR DE CATALUÑA,PARTIDO ECOLÓGICO ESPAÑOL,ACCIÓN POR CEUTA,ASOCIACIÓN DE DEMÓCRATAS INDEPENDIENTES VASCOS,CONFEDERACIÓN DE PARTIDOS CONSERVADORES,CENTRO POPULAR",
            "PCE": "PARTIDO COMUNISTA DE ESPAÑA",
            "PCPV": "PARTIDO COMUNISTA DE ESPAÑA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "PSA": "PARTIDO SOCIALISTA DE ANDALUCIA",
            "PAR": "PARTIDO ARAGONES",
            "UPN": "UNION DEL PUEBLO NAVARRO",
            "UPC": "UNION DEL PUEBLO CANARIO",
            "PSUC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA",
            "UN": "FUERZA NUEVA,FALANGE ESPAÑOLA DE LAS J.O.N.S.,CÍRCULOS DOCTRINALES JOSÉ ANTONIO,COMUNION TRADICIONALISTA,AGRUPACION DE JUVENTUDES TRADICIONALISTAS",
        },
        "2": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_1982
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "UCD": "UNION DE CENTRO DEMOCRATICO",
            "CDS": "CENTRO DEMOCRATICO Y SOCIAL",
            "CD": "ALIANZA POPULAR,ACCION CIUDADANA LIBERAL,PARTIDO DEMÓCRATA PROGRESISTA,RENOVACIÓN ESPAÑOLA,PARTIDO POPULAR DE CATALUÑA,PARTIDO ECOLÓGICO ESPAÑOL,ACCIÓN POR CEUTA,ASOCIACIÓN DE DEMÓCRATAS INDEPENDIENTES VASCOS,CONFEDERACIÓN DE PARTIDOS CONSERVADORES,CENTRO POPULAR",
            "PCE": "PARTIDO COMUNISTA DE ESPAÑA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "PSUC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA",
        },
        "3": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_1986
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSC": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "CP": "ALIANZA POPULAR,PARTIDO DEMOCRATA POPULAR,PARTIDO LIBERAL,UNIO VALENCIANA,UNION DEL PUEBLO NAVARRO,PARTIDO ARAGONES,CENTRISTAS DE GALICIA",
            "IU": "PARTIDO COMUNISTA DE ESPAÑA,PARTIT SOCIALISTA UNIFICAT DE CATALUNYA,CANDIDATURA UNITARIA DE TRABAJADORES/AS,PARTIDO COMUNISTA DE LOS PUEBLOS DE ESPAÑA,PARTIDO DE ACCION SOCIALISTA,IZQUIERDA REPUBLICANA,FEDERACION PROGRESISTA,PARTIDO HUMANISTA,PARTIDO CARLISTA",
            "UEC": "PARTIT SOCIALISTA UNIFICAT DE CATALUNYA,ENTESA DELS NACIONALISTES D'ESQUERRA",
            "CDS": "CENTRO DEMOCRATICO Y SOCIAL",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "CG": "COALICION GALEGA",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "UV": "UNIO VALENCIANA",
            "AIC": "AGRUPACIONES INDEPENDIENTES DE CANARIAS",
            "PAR": "PARTIDO ARAGONES",
        },
        "4": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_1989
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-A": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI (PSOE)",
            "PP": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PP-CG": "PARTIDO POPULAR,COALICION GALEGA",
            "CDS": "CENTRO DEMOCRATICO Y SOCIAL",
            "IU": "IZQUIERDA UNIDA",
            "IU-A": "IZQUIERDA UNIDA",
            "IU-CA": "IZQUIERDA UNIDA",
            "IU-EU": "IZQUIERDA UNIDA",
            "IU-EUPV": "IZQUIERDA UNIDA,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "HB": "HERRI BATASUNA",
            "IC": "INICIATIVA PER CATALUNYA VERDS",
            "EE": "EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "EA": "EUSKO ALKARTASUNA",
            "PA": "PARTIDO SOCIALISTA DE ANDALUCIA",
            "UV": "UNIO VALENCIANA",
            "PAR": "PARTIDO ARAGONES",
            "AIC": "AGRUPACIONES INDEPENDIENTES DE CANARIAS",
        },
        "5": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_1993
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-A": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PP": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "IU": "IZQUIERDA UNIDA",
            "IU-A": "IZQUIERDA UNIDA",
            "IU-CA": "IZQUIERDA UNIDA",
            "IU-EU": "IZQUIERDA UNIDA",
            "IU-EUPV": "IZQUIERDA UNIDA,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EA-EE": "EUSKO ALKARTASUNA,EUSKADIKO EZKERRA-IZQUIERDA PARA EL SOCIALISMO",
            "IC": "INICIATIVA PER CATALUNYA VERDS",
            "CC": "COALICION CANARIA",
            "UV": "UNIO VALENCIANA",
            "HB": "HERRI BATASUNA",
            "PAR": "PARTIDO ARAGONES",
        },
        "6": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_1996
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-A": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PP": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "IU": "IZQUIERDA UNIDA",
            "IU-LV": "IZQUIERDA UNIDA",
            "IU-LV-CA": "IZQUIERDA UNIDA LOS VERDES-CONVOCATORIA POR ANDALUCIA",
            "IU-EUPV": "IZQUIERDA UNIDA,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "IU-EB": "IZQUIERDA UNIDA",
            "EUPV": "ESQUERRA UNIDA DEL PAIS VALENCIA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EA": "EUSKO ALKARTASUNA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "CC": "COALICION CANARIA",
            "UV": "UNIO VALENCIANA",
            "IC-EV": "INICIATIVA PER CATALUNYA VERDS",
        },
        "7": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_2000
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOE-PROGRESISTAS": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC(PSC-PSOE)": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSDEG-PSOE-PROGRESISTAS": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE (PSOE-PROGRESISTAS)": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PP": "PARTIDO POPULAR",
            "PP-UPN": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PP-UPM": "PARTIDO POPULAR,UNION DEL PUEBLO MELILLENSE",
            "IU": "IZQUIERDA UNIDA",
            "IU-CM": "IZQUIERDA UNIDA DE LA COMUNIDAD DE MADRID",
            "EUPV": "ESQUERRA UNIDA DEL PAIS VALENCIA",
            "IU-LV-CA": "IZQUIERDA UNIDA LOS VERDES-CONVOCATORIA POR ANDALUCIA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "IC-V": "INICIATIVA PER CATALUNYA VERDS",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EA": "EUSKO ALKARTASUNA",
            "CC": "COALICION CANARIA",
            "CHA": "CHUNTA ARAGONESISTA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "PA": "PARTIDO SOCIALISTA DE ANDALUCIA",
        },
        "8": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_2004
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC(PSC-PSOE)": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSOEDEANDALUCÍA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE(PSOE)": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PP": "PARTIDO POPULAR",
            "PPDEC": "PARTIDO POPULAR",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "IU": "IZQUIERDA UNIDA",
            "ICV-EUIA": "INICIATIVA PER CATALUNYA VERDS,ESQUERRA UNIDA I ALTERNATIVA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "NA-BAI": "ARALAR,EUSKO ALKARTASUNA,BATZARRE-ASAMBLEA DE IZQUIERDAS,EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EA": "EUSKO ALKARTASUNA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "CC": "COALICION CANARIA",
            "NC": "COALICION CANARIA",
            "CHA": "CHUNTA ARAGONESISTA",
        },
        "9": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_2008
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC(PSC-PSOE)": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSE-EE(PSOE)": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSOEDEANDALUCÍA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "IU-ALTERNATIVA": "IZQUIERDA UNIDA",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "UPN": "UNION DEL PUEBLO NAVARRO",
            "NA-BAI": "ARALAR,EUSKO ALKARTASUNA,BATZARRE-ASAMBLEA DE IZQUIERDAS,EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "UPYD": "UNION PROGRESO Y DEMOCRACIA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "ICV-EUIA": "INICIATIVA PER CATALUNYA VERDS,ESQUERRA UNIDA I ALTERNATIVA",
            "CC": "COALICION CANARIA",
            "CC-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO",
        },
        "10": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_2011
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PP": "PARTIDO POPULAR",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "PP-EU": "PARTIDO POPULAR,EXTREMADURA UNIDA",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "IZQ-PLU": "IZQUIERDA UNIDA",
            "IU-IX": "IZQUIERDA UNIDA DE ASTURIAS-IZQUIERDA XUNIDA D'ASTURIES",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "CIU": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,UNION DEMOCRATICA DE CATALUÑA",
            "ERC-RI.CAT": "ESQUERRA REPUBLICANA DE CATALUNYA,CATALUNYA SÍ",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
            "UPYD": "UNION PROGRESO Y DEMOCRACIA",
            "CC-NC-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO,NUEVA CANARIAS",
            "GB": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO,AGRUPACION ATARRABIA - ATARRABIA TALDEA",
            "AMAIUR": "EUSKO ALKARTASUNA,ALTERNATIBA ERAIKITZEN,ARALAR",
            "FORO": "FORO ASTURIAS",
            "COMPROMÍS-Q": "MÉS-COMPROMÍS,INICIATIVA DEL POBLE VALENCIA,ESQUERRA ECOLOGISTA-VERDS,VERDES EQUO",
        },
        "11": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_2015
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSOE-NCA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL,NUEVA CANARIAS",
            "PP": "PARTIDO POPULAR",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "PP-FORO": "PARTIDO POPULAR,FORO ASTURIAS",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "PODEMOS": "PODEMOS",
            "PODEMOS-EN MAREA-ANOVA-EU": "PODEMOS,EN MAREA,ANOVA - IRMANDADE NACIONALISTA,IZQUIERDA UNIDA",
            "PODEMOS-COMPROMÍS": "PODEMOS,MÉS-COMPROMÍS,INICIATIVA DEL POBLE VALENCIA,VERDES EQUO",
            "POD-AAA EN COMÚN": "PODEMOS,AAeC",
            "EN COMÚ": "PODEMOS,CATALUNYA EN COMÚ",
            "IU-UPEC": "IZQUIERDA UNIDA",
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "ERC-CATSÍ": "ESQUERRA REPUBLICANA DE CATALUNYA,CATALUNYA SÍ",
            "DL": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,DC",
            "CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO",
        },
        "12": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_2016
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSDG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PSOE-NCA": "PARTIDO SOCIALISTA OBRERO ESPAÑOL,NUEVA CANARIAS",
            "PP": "PARTIDO POPULAR",
            "PP-FORO": "PARTIDO POPULAR,FORO ASTURIAS",
            "PP-PAR": "PARTIDO POPULAR,PARTIDO ARAGONES",
            "UPN-PP": "PARTIDO POPULAR,UNION DEL PUEBLO NAVARRO",
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "UP": "PODEMOS,IZQUIERDA UNIDA,VERDES EQUO,BATZARRE-ASAMBLEA DE IZQUIERDAS,IZQUIERDA ASTURIANA,MÉS PER MENORCA,MÉS PER MALLORCA,ARA EIVISSA,IZQUIERDA ASTURIANA,CONSTUYENDO LA IZQUIERDA-ALTERNATIVA SOCIALISTA,SEGOVIEMOS,IZQUIERDA CASTELLANA,DEMOCRACIA PARTICIPATIVA,CHUNTA ARAGONESISTA,MOVIMIENTO CORRIENTE ROJA",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=1611
            "ECP": "BARCELONA EN COMÚ,PODEMOS,INICIATIVA PER CATALUNYA VERDS,ESQUERRA UNIDA I ALTERNATIVA",
            "EM-P-A-EU": "EN MAREA,PODEMOS,ANOVA - IRMANDADE NACIONALISTA,IZQUIERDA UNIDA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "CDC": "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA",
            "ERC-CATSÍ": "ESQUERRA REPUBLICANA DE CATALUNYA,CATALUNYA SÍ",
            "CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO",
            "C-P-EUPV": "MÉS-COMPROMÍS,INICIATIVA DEL POBLE VALENCIA,VERDES EQUO,PODEMOS,ESQUERRA UNIDA DEL PAIS VALENCIA",
            "UPM": "PODEMOS,ESQUERRA UNIDA DE LES ILLES BALEARS,MÉS PER MALLORCA",
        },
        "13": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_abril_de_2019
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSE-EE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PP": "PARTIDO POPULAR",
            "PP-FORO": "PARTIDO POPULAR,FORO ASTURIAS",
            "UP": "PODEMOS,IZQUIERDA UNIDA,VERDES EQUO",
            "ECP": "PODEMOS,CATALUNYA EN COMÚ,ESQUERRA UNIDA I ALTERNATIVA",
            "EC-UP": "PODEMOS,IZQUIERDA UNIDA",
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "JXCAT-JUNTS": "PARTIT DEMÒCRATA EUROPEU CATALÀ,CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA,JUNTS PER CATALUNYA",
            "ERC-S": "ESQUERRA REPUBLICANA DE CATALUNYA",
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "VOX": "VOX",
            "CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO",
            "NA+": "UNIÓN DEL PUEBLO NAVARRO,PARTIDO POPULAR,CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "PRC": "PARTIDO REGIONALISTA DE CANTABRIA",
            "C:B-I-V": "MÉS-COMPROMÍS,INICIATIVA DEL POBLE VALENCIA,VERDES EQUO",
        },
        "14": {  # https://es.wikipedia.org/wiki/Elecciones_generales_de_Espa%C3%B1a_de_noviembre_de_2019
            "PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PSC-PSOE": "PARTIT DELS SOCIALISTES DE CATALUNYA (PSC-PSOE)",
            "PSE-EE-PSOE": "PARTIDO SOCIALISTA DE EUSKADI-EUSKADIKO EZKERRA (PSOE)",
            "PSDEG-PSOE": "PARTIDO SOCIALISTA OBRERO ESPAÑOL",
            "PP": "PARTIDO POPULAR",
            "PP-FORO": "PARTIDO POPULAR,FORO ASTURIAS",  # http://www.juntaelectoralcentral.es/cs/jec/documentos/JEPAsturias-COALICION%20PP-FORO.pdf
            "UP": "PODEMOS,IZQUIERDA UNIDA,BATZARRE-ASAMBLEA DE IZQUIERDAS,ALTO ARAGÓN EN COMÚN",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32389
            "ECP-GUAYEM EL CANVI": "EN COMÚ PODEM,CATALUNYA EN COMÚ,PODEMOS",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32440
            "EC-UP": "PODEMOS,ESQUERDA UNIDA GALEGA",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32444
            "MÁS PAÍS-EQUO": "MÁS PAÍS,VERDES EQUO",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32446
            "EAJ-PNV": "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO",
            "EH BILDU": "EUSKAL HERRIA BILDU",
            "JXCAT-JUNTS": "PARTIT DEMÒCRATA EUROPEU CATALÀ,JUNTS PER CATALUNYA",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32427
            "JXCAT-JUNTS (JUNTS)": "PARTIT DEMÒCRATA EUROPEU CATALÀ,JUNTS PER CATALUNYA",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32427
            "JXCAT-JUNTS (PDECAT)": "PARTIT DEMÒCRATA EUROPEU CATALÀ,JUNTS PER CATALUNYA",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32427
            "ERC-S": "ESQUERRA REPUBLICANA DE CATALUNYA",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32424
            "CUP-PR": "CANDIDATURA D'UNITAT POPULAR,CAPGIREM",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32436
            "CCA-PNC-NC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO,NUEVA CANARIAS",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32442
            "NC-CCA-PNC": "COALICION CANARIA,PARTIDO NACIONALISTA CANARIO,NUEVA CANARIAS",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32442
            "NA+": "UNION DEL PUEBLO NAVARRO,CIUDADANOS-PARTIDO DE LA CIUDADANIA",  # http://www.juntaelectoralcentral.es/cs/jec/documentos/JEPNavarra-COALICION%20NAVARRA%20SUMA.pdf
            "¡TERUEL EXISTE!": "TERUEL EXISTE",
            "MÉS COMPROMÍS": "MÉS-COMPROMÍS,INICIATIVA DEL POBLE VALENCIA,VERDS EQUO DEL PAÍS VALENCIÀ,COALICIO COMPROMIS,MÁS PAÍS",  # https://app.juntaelectoralcentral.es/svtjec/descargarFichero?tipo=tipoCoalicion&codigoCoalicion=32447
            "CS": "CIUDADANOS-PARTIDO DE LA CIUDADANIA",
            "VOX": "VOX",
            "PRC": "PARTIDO REGIONALISTA DE CANTABRIA",
            "BNG": "BLOQUE NACIONALISTA GALEGO",
        },
    }

    def get_positions(self, institution_name):
        return Position.objects.filter(
            period__institution__name=institution_name,
            period__number__gte=0,
        )

    def get_party(self, short_name):
        short_name = short_name.strip().upper()
        short_name = self.parties_group.get(short_name, short_name)
        result = self.parties_cache.get(short_name)
        if result:
            return result
        result = Party.objects.filter(short_name__iexact=short_name).first()
        if result:
            self.parties_cache[short_name] = result
            return result
        return None

    def handle_special_cases(self, position):
        leg = position.metadata["www.congreso.es"]["idLegislatura"]
        code = position.metadata["www.congreso.es"]["codParlamentario"]

        if leg == 8 and code == 331:
            return "PARTIDO POPULAR"

        return None

    def handle(self, *args, **options):
        for position in self.get_positions("Parlamento de España"):
            name = position.metadata["www.congreso.es"]["formacion"].strip().upper()

            if self.handle_special_cases(position):
                continue

            if not self.parties_group[str(position.period.number)].get(name):
                print(name, "                 ->", position)

        # parties = set()

        # for leg in self.parties_group:
        #     for coa in self.parties_group[leg]:
        #         for party in self.parties_group[leg][coa].split(","):
        #             parties.add(party)

        # for party in sorted(parties):
        #     print(party)
