# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-03-18 11:38

import core.models.BaseAbstract
import core.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid
import world.services.staticfiles


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adm0",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Nombre completo", max_length=100
                    ),
                ),
                (
                    "iso_name",
                    models.CharField(
                        db_index=True, help_text="Nombre según ISO-3166", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código Alpha-2 según ISO-3166-1",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True,
                        help_text="Bandera o representación",
                        null=True,
                        storage=core.storage.FileSystemOverwriteStorage(),
                        upload_to=world.services.staticfiles.adm_flag_path,
                        validators=[world.services.staticfiles.validate_flag_filetype],
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm0",
                "verbose_name_plural": "Adm0",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Adm1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Nombre completo", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código completo (<adm0>_<adm1>): es_and para España-Andalucía",
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        help_text="Adm0 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm1",
                        to="world.adm0",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm1",
                "verbose_name_plural": "Adm1",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Adm2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Nombre completo", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código completo (<adm0>_<adm2>): es_sev para España-Sevilla",
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        help_text="Adm0 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm2",
                        to="world.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        help_text="Adm1 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm2",
                        to="world.adm1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm2",
                "verbose_name_plural": "Adm2",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Adm3",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Nombre completo", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código completo (<adm0>_<adm3>): es_sev_aljarafe para España-Aljarafe",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        help_text="Adm0 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm3",
                        to="world.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        help_text="Adm1 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm3",
                        to="world.adm1",
                    ),
                ),
                (
                    "adm2",
                    models.ForeignKey(
                        help_text="Adm2 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm3",
                        to="world.adm2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm3",
                "verbose_name_plural": "Adm3",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Adm4",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Nombre completo", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código completo (<adm0>_<adm2_<adm4>): es_sev_gines para España-Sevilla-Gines",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        help_text="Adm0 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        help_text="Adm1 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm1",
                    ),
                ),
                (
                    "adm2",
                    models.ForeignKey(
                        help_text="Adm2 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm2",
                    ),
                ),
                (
                    "adm3",
                    models.ForeignKey(
                        help_text="Adm3 al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm4",
                "verbose_name_plural": "Adm4",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
