# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-02-04 11:06

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adm0",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=core.models.json_default_field)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("iso_name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=2, unique=True)),
            ],
            options={
                "verbose_name": "Adm0",
                "verbose_name_plural": "Adm0",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Adm1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=core.models.json_default_field)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=6, unique=True)),
                (
                    "adm0",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm1",
                        to="world.adm0",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm1",
                "verbose_name_plural": "Adm1",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Adm2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=core.models.json_default_field)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=6, unique=True)),
                (
                    "adm0",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm2",
                        to="world.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm2",
                        to="world.adm1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm2",
                "verbose_name_plural": "Adm2",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Adm3",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=core.models.json_default_field)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "adm0",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm3",
                        to="world.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm3",
                        to="world.adm1",
                    ),
                ),
                (
                    "adm2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm3",
                        to="world.adm2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm3",
                "verbose_name_plural": "Adm3",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Adm4",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=core.models.json_default_field)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "adm0",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm1",
                    ),
                ),
                (
                    "adm2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm2",
                    ),
                ),
                (
                    "adm3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm4",
                        to="world.adm3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adm4",
                "verbose_name_plural": "Adm4",
                "ordering": ("id",),
            },
        ),
    ]
