# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-03-02 17:43

import core.storage
from django.db import migrations, models
import world.services.staticfiles


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0006_adm0_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adm0",
            name="flag",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storage.FileSystemOverwriteStorage(),
                upload_to=world.services.staticfiles.adm_flag_path,
                validators=[world.services.staticfiles.validate_flag_filetype],
            ),
        ),
    ]
