# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-03-18 11:38

import core.models.BaseAbstract
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre completo del partido político",
                        max_length=255,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        db_index=True,
                        help_text="Siglas del partido político",
                        max_length=255,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Color principal del partido político", max_length=7
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        help_text="País al que pertenece el partido político",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parties",
                        to="world.adm0",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "db_table": "organizations_party",
                "ordering": ("id",),
                "unique_together": {("short_name", "adm0"), ("name", "adm0")},
            },
        ),
    ]
