# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-04-02 15:07

import core.models.BaseAbstract
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("world", "0005_fill_spain_adm3_adm4"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre completo de la candidatura",
                        max_length=255,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Siglas de la candidatura",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.URLField(
                        blank=True,
                        help_text="Fuente de la candidatura",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidatura",
                "verbose_name_plural": "Candidaturas",
                "db_table": "organizations_candidacy",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Foundation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre completo de la fundación",
                        max_length=255,
                    ),
                ),
                (
                    "start",
                    models.DateField(help_text="Fecha de creación de la fundación"),
                ),
                (
                    "end",
                    models.DateField(help_text="Fecha de disolución de la fundación"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Domicilio social de la fundación",
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de la fundación",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "web",
                    models.URLField(
                        blank=True,
                        help_text="Página web de la fundación",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fundación",
                "verbose_name_plural": "Fundaciones",
                "db_table": "organizations_foundation",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre completo del partido político",
                        max_length=255,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Siglas del partido político",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de registro. Números mayores de 100000 son partidos disueltos",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000",
                        help_text="Color principal del partido político",
                        max_length=7,
                        validators=[core.validators.validate_hex_color],
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("adm0", "Estatal"),
                            ("adm1", "CCAA"),
                            ("adm2", "Provincial"),
                            ("adm3", "Regional"),
                            ("adm4", "Municipal"),
                            ("adm5", "Sub-municipal"),
                        ],
                        default="adm0",
                        help_text="Ámbito (estatal, municipal...)",
                        max_length=4,
                    ),
                ),
                (
                    "founded",
                    models.DateField(
                        blank=True, help_text="Fecha de creación del partido", null=True
                    ),
                ),
                ("start", models.DateField(help_text="Fecha de registro del partido")),
                ("end", models.DateField(help_text="Fecha de disolución del partido")),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Domicilio social del partido", null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email del partido",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "web",
                    models.URLField(
                        blank=True,
                        help_text="Página web del partido",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        help_text="País al que pertenece el partido político",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parties",
                        to="world.adm0",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "db_table": "organizations_party",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PoliticalSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Nombre del espacio", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Espacio político",
                "verbose_name_plural": "Espacios políticos",
                "db_table": "organizations_politicalspace",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PartyCandidacy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Fecha del acuerdo", null=True
                    ),
                ),
                ("source", models.TextField(help_text="Url completa de la fuente")),
                (
                    "candidacy",
                    models.ForeignKey(
                        help_text="Candidatura a la que hace referencia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_candidatures",
                        to="organizations.candidacy",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Partido al que hace referencia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_candidatures",
                        to="organizations.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participación en candidatura",
                "verbose_name_plural": "Participaciones en candidaturas",
                "db_table": "organizations_partycandidacy",
                "ordering": ("id",),
            },
        ),
    ]
