# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="party",
            options={"ordering": ("id",), "verbose_name_plural": "Parties"},
        ),
    ]
