# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-04-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("positions", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidacy",
            name="period",
            field=models.ForeignKey(
                help_text="Periodo al cual se presenta la candidatura",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidatures",
                to="positions.period",
            ),
        ),
        migrations.AddField(
            model_name="candidacy",
            name="political_space",
            field=models.ForeignKey(
                blank=True,
                help_text="Espacio político al que pertenece la candidatura",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidatures",
                to="organizations.politicalspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="party",
            unique_together={("name", "adm0")},
        ),
        migrations.AlterUniqueTogether(
            name="candidacy",
            unique_together={("name", "period"), ("short_name", "period")},
        ),
    ]
