# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_party_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Código único de registro. Números mayores de 100000 son no encotrados en registro",
                max_length=255,
                unique=True,
            ),
        ),
    ]
