# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_fill_spain_goverment_persons"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biographysource",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="birthdatesource",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ("id",)},
        ),
    ]
