# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-04-02 15:07

import core.models.BaseAbstract
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
        ("world", "0005_fill_spain_adm3_adm4"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre formal de la institución",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "adm0",
                    models.ForeignKey(
                        help_text="Adm0 (país) al que pertenece la institución",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions",
                        to="world.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        help_text="Adm1 (ccaa) al que pertenece la institución",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions",
                        to="world.adm1",
                    ),
                ),
                (
                    "adm2",
                    models.ForeignKey(
                        help_text="Adm2 (provincia) al que pertenece la institución",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions",
                        to="world.adm2",
                    ),
                ),
                (
                    "adm3",
                    models.ForeignKey(
                        help_text="Adm3 (región) al que pertenece la institución",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions",
                        to="world.adm3",
                    ),
                ),
                (
                    "adm4",
                    models.ForeignKey(
                        help_text="Adm4 (municipio) al que pertenece la institución",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions",
                        to="world.adm4",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "db_table": "positions_institution",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre formal del periodo (Legislatura X)",
                        max_length=250,
                    ),
                ),
                ("number", models.IntegerField(help_text="Número del periodo (orden)")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código del período (V, VI, VII...)",
                        max_length=250,
                    ),
                ),
                ("start", models.DateField(help_text="Fecha de inicio del periodo")),
                (
                    "end",
                    models.DateField(help_text="Fecha de finalización del periodo"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institución a la que pertenece el periodo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="positions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo",
                "verbose_name_plural": "Periodos",
                "db_table": "positions_period",
                "ordering": ("id",),
                "abstract": False,
                "unique_together": {
                    ("code", "institution"),
                    ("name", "institution"),
                    ("number", "institution"),
                },
            },
        ),
        migrations.CreateModel(
            name="PositionParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Nombre oficial del cargo (Secretario, Presidenta...)"
                    ),
                ),
                ("start", models.DateField(help_text="Fecha de inicio del cargo")),
                ("end", models.DateField(help_text="Fecha de finalización del cargo")),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Partido al que pertenece el cargo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_positions",
                        to="organizations.party",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Persona que ostenta el cargo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_positions",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo en partido",
                "verbose_name_plural": "Cargos en partidos",
                "db_table": "positions_partyposition",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la instancia del modelo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la instancia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la instancia"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=core.models.BaseAbstract.json_default_field
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Nombre corto del cargo (Diputado, Ministro...)",
                        max_length=255,
                    ),
                ),
                (
                    "full_name",
                    models.TextField(
                        help_text="Nombre oficial del cargo (Diputado de la Legislatura VII...)"
                    ),
                ),
                ("start", models.DateField(help_text="Fecha de inicio del cargo")),
                ("end", models.DateField(help_text="Fecha de finalización del cargo")),
                (
                    "candidacy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Candidatura que consigue el cargo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="organizations.candidacy",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="Periodo vinculado al cargo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="positions.period",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Persona que ostenta el cargo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "db_table": "positions_position",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
