# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-02-04 12:12

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0002_fill_spanish_institutions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=core.models.json_default_field)),
                ("name", models.CharField(db_index=True, max_length=250)),
                ("number", models.IntegerField()),
                ("code", models.CharField(db_index=True, max_length=250)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="positions.institution",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("name", "institution"),
                    ("number", "institution"),
                    ("code", "institution"),
                },
            },
        ),
    ]
