# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0005_fill_spain_governors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="period",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="positionparty",
            options={"ordering": ("id",)},
        ),
    ]
